apiVersion: v1
entries:
  eidolon-operator-chart:
  - apiVersion: v2
    appVersion: 0.0.58
    created: "2024-09-03T00:13:42.927404869Z"
    description: A Helm chart for Kubernetes
    digest: 331b4d7212acc7ed135c3d44d548c55945073fb84109fec9188d4edece84c2da
    name: eidolon-operator-chart
    type: application
    urls:
    - https://eidolonai.com/charts/eidolon-operator-chart-0.0.58.tgz
    version: 0.0.58
generated: "2024-09-03T00:13:42.926446705Z"
