apiVersion: eidolon/v1
kind: Reference
metadata:
  name: frugal_cpu

spec:
  implementation: "eidos_sdk.cpu.conversational_agent_cpu.ConversationalAgentCPU"
  cpu:
    spec:
      llm_unit:
        spec:
          force_json: 'True'
          max_tokens: '3000'
          model: gpt-3.5-turbo-1106
          temperature: '.1'
      max_num_function_calls: '20'
