apiVersion: server.eidolonai.com/v1alpha1
kind: Agent
metadata:
  name: qa

spec:
  implementation: eidolon_examples.getting_started.2_custom_agents.qa.QualityAssurance
  agent_refs: ["hello_world"]
  apu: frugal_cpu
