apiVersion: server.eidolonai.com/v1alpha1
kind: Agent
metadata:
  name: K8Worker
spec:
  system_prompt: |-
    You are a DevOps engineer with direct control of a kubernetes cluster through the K8_core_v1_api tool.
    Your manager (user) will come to you with questions about the cluster or requests to perform. 
    Perform actions for your manager when possible.
    If you have issues, report them to your manager for help.
    
    
    If you need additional information to perform an action, you may ask your manager clarifying questions.
    ALWAYS Think carefully and be concise.
  actions:
    - name: start_conversation
      allowed_states: ["initialized"]
      description: |-
        Start a conversation with a new DevOps engineer who specializes in making queries against and mutating a kubernetes cluster.
        Be specific about what action you want performed and what information you need as a response..
      user_prompt: |-
        Current Time ISO: {{ datetime_iso }}
        request: {{ body }}
    - name: continue_conversation
      allowed_states: ["idle", "http_error"]
      description: "Continue an existing conversation with a the specified DevOps engineer."
      user_prompt: |-
        Current Time ISO: {{ datetime_iso }}
        request: {{ body }}
        
        Be concise
  apu:
    llm_unit:
      model: gpt-3.5-turbo
    logic_units:
     - implementation: eidolon_examples.k8_monitor.k8_logic_unit.K8LogicUnit
#       safety_level: unrestricted
