replicaCount: 1

image:
  repository: eidolonai/eidolon-operator
  pullPolicy: IfNotPresent
  tag: "latest"  # Set this to your operator version

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
securityContext: {}

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

nodeSelector: {}
tolerations: []
affinity: {}

# Operator-specific configurations
config:
  logLevel: info
  watchNamespace: ""  # Set to a specific namespace or leave empty for cluster-wide

# CRDs
crds:
  create: true

# RBAC
rbac:
  create: true