---
apiVersion: eidolon/v1
kind: Reference
metadata:
  name: ClaudeOpus
  annotations:
    - title: "Claude Opus"
spec:
  implementation: APU
  audio_unit: OpenAiSpeech
  image_unit: OpenAIImageUnit
  llm_unit:
    implementation: AnthropicLLMUnit
    model: "claude-3-opus-20240229"
---
apiVersion: eidolon/v1
kind: Reference
metadata:
  name: claude-3-opus-20240229
spec:
  implementation: LLMModel
  human_name: Claude Opus
  name: "claude-3-opus-20240229"
  input_context_limit: 200000
  output_context_limit: 4096
  supports_tools: False
  supports_image_input: True
  supports_audio_input: False