apiVersion: server.eidolonai.com/v1alpha1
kind: Machine

metadata:
  name: DEFAULT

---
apiVersion: server.eidolonai.com/v1alpha1
kind: Machine

metadata:
  name: local_dev

spec:
  symbolic_memory: LocalSymbolicMemory
