---
apiVersion: server.eidolonai.com/v1alpha1
kind: Reference
metadata:
  name: MistralMedium
  annotations:
    - title: "Mistral Medium"
spec:
  implementation: ConversationalAPU
  llm_unit:
    implementation: MistralGPT
    model: "mistral-medium-latest"
---
apiVersion: server.eidolonai.com/v1alpha1
kind: Reference
metadata:
  name: "mistral-medium-latest"
spec:
  implementation: LLMModel
  human_name: Mistral Medium
  name: "mistral-medium-latest"
  input_context_limit: 32000
  output_context_limit: 4096
  supports_tools: False
  supports_image_input: False
  supports_audio_input: False
