---
apiVersion: eidolon/v1
kind: Reference
metadata:
  name: GPT3.5-turbo
  annotations:
    - title: "OpenAI GPT 3.5 Turbo"
spec:
    implementation: APU
    audio_unit: OpenAiSpeech
    image_unit: OpenAIImageUnit
    llm_unit:
      implementation: OpenAIGPT
      model: "gpt-3.5-turbo"
---
apiVersion: eidolon/v1
kind: Reference
metadata:
  name: "gpt-3.5-turbo"
spec:
  implementation: LLMModel
  human_name: "GPT-3.5 Turbo"
  name: "gpt-3.5-turbo"
  input_context_limit: 16385
  output_context_limit: 4096
  supports_tools: True
  supports_image_input: False
  supports_audio_input: False