---
apiVersion: server.eidolonai.com/v1alpha1
kind: Reference
metadata:
  name: GPT4-turbo
  annotations:
    - title: "OpenAI GPT 4.0 Turbo"
spec:
    implementation: ConversationalAPU
    audio_unit: OpenAiSpeech
    image_unit: OpenAIImageUnit
    llm_unit:
      implementation: OpenAIGPT
      model: "gpt-4-turbo"
---
apiVersion: server.eidolonai.com/v1alpha1
kind: Reference
metadata:
  name: "gpt-4-turbo"
spec:
  implementation: LLMModel
  human_name: "GPT-4 Turbo"
  name: "gpt-4-turbo"
  input_context_limit: 128000
  output_context_limit: 4096
  supports_tools: True
  supports_image_input: False
  supports_audio_input: False