---
apiVersion: eidolon/v1
kind: Reference
metadata:
  name: GPT4-turbo
  annotations:
    - title: "OpenAI GPT 4.0 Turbo"
spec:
    implementation: APU
    llm_unit:
      implementation: OpenAIGPT
      model: "gpt-4-turbo-preview"
---
apiVersion: eidolon/v1
kind: Reference
metadata:
  name: "gpt-4-turbo-preview"
spec:
  implementation: LLMModel
  human_name: "GPT-4 Turbo Preview"
  name: "gpt-4-turbo-preview"
  input_context_limit: 128000
  output_context_limit: 4096
  supports_tools: True
  supports_image_input: True
  supports_audio_input: False