apiVersion: server.eidolonai.com/v1alpha1
kind: Machine
spec:
  symbolic_memory:
    implementation: "eidolon_ai_sdk.memory.mongo_symbolic_memory.MongoSymbolicMemory"
    mongo_database_name: "eidolon"
