---
apiVersion: server.eidolonai.com/v1alpha1
kind: Reference
metadata:
  name: AuthenticationProcessor
spec:
  implementation: AzureJWTProcessor
#  client_id: ###  # app id set here or via envar @ AZURE_CLIENT_ID
#  tenant_id: ###  # tenant id set here or via envar @ AZURE_TENANT_ID
---
apiVersion: server.eidolonai.com/v1alpha1
kind: Reference
metadata:
  name: FunctionalAuthorizer
spec: GlobPatternFunctionalAuthorizer
