---
# First We need to configure our openai connection handler to use the Azure
apiVersion: server.eidolonai.com/v1alpha1
kind: Reference
metadata:
  name: OpenAIConnectionHandler
spec:
  implementation: AzureOpenAIConnectionHandler
  azure_endpoint: https://testinstancename.openai.azure.com/  # This is the endpoint of the Azure OpenAI service
---
# Then we need to point our model to the Azure model deployment
apiVersion: server.eidolonai.com/v1alpha1
kind: Reference
metadata:
  name: "gpt-4-turbo-preview"
spec:
  name: 4turbo  # This is the name of the model deployment in Azure