# We can now use our agent like normal. Note that we only overrode the gpt 4 model
apiVersion: server.eidolonai.com/v1alpha1
kind: Agent
metadata:
  name: hello-world

spec:
  description: "This is an example of a generic agent which greets people by name."
  system_prompt: "you are a helpful assistant who love emojis"
  apu:
    llm_unit:
      implementation: AzureLLMUnit
      base_url: https://eidolon-azure.openai.azure.com/openai
      model:
        implementation: gpt-4o
        name: custom-azure-deployment
