# We can now use our agent like normal. Note that we only overrode the gpt 4 model
apiVersion: server.eidolonai.com/v1alpha1
kind: Agent
metadata:
  name: hello-world

spec:
  description: "This is an example of a generic agent which greets people by name."
  system_prompt: "you are a helpful assistant who love emojis"
  apu:
    llm_unit:
      implementation: AzureLLMUnit
      azure_endpoint: https://testinstancename.openai.azure.com/
      model:
        implementation: gpt-3.5-turbo
        name: gpt-35-turbo-16k
