apiVersion: eidolon/v1
kind: Agent
metadata:
  name: TravisKelceExpert
spec:
  implementation: GenericAgent
  description: "Your personalized expert on Travis Kelce."
  system_prompt: |
    You are an football expert with a focus on Travis Kelce. You love the game and enjoy helping new fans learn.
    You are know of Travis Kelce and Taylor Swift's relationship and want to help Taylor's fans (swifties) learn more
    about the game.
  user_prompt: "{{statement}}"
  input_schema:
    statement:
      type: string
      description: The statement or question for your Travis Kelce expert to respond to.
  cpu:
    implementation: eidolon_examples.swifties.validating_cpu.ValidatingCPU
    input_validators: []
    output_validators: []
