# permissions for end users to edit references.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: reference-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: eidolon-operator
    app.kubernetes.io/part-of: eidolon-operator
    app.kubernetes.io/managed-by: kustomize
  name: reference-editor-role
rules:
- apiGroups:
  - server.eidolonai.com
  resources:
  - references
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - server.eidolonai.com
  resources:
  - references/status
  verbs:
  - get
