apiVersion: eidolon/v1
kind: Agent
metadata:
  name: conversational_agent
spec:
  system_prompt: "You are a helpful assistant. Please respond using markdown unless told otherwise by the user. Output all multi-media content as embedded content including image, video, and audio."
  actions:
    - name: "converse"
      description: "A copilot that engages with the user."
      allow_file_upload: true
  apus:
    - apu: MistralSmall
      title: Mistral Small
    - apu: MistralMedium
      title: Mistral Medium
    - apu: MistralLarge
      title: Mistral Large
    - apu: GPT3.5-turbo
      title: GPT3.5 Turbo
    - apu: GPT4-turbo
      title: GPT4 Turbo
      default: true
    - apu: ClaudeOpus
      title: Claude Opus
    - apu: ClaudeSonnet
      title: Claude Sonnet
    - apu: ClaudeHaiku
      title: Claude Haiku
