apiVersion: eidolon/v1
kind: Agent
metadata:
  name: conversational_agent
spec:
  system_prompt: "You are a helpful assistant. Please respond using markdown unless told otherwise by the user."
  actions:
    - name: "converse"
      description: "A copilot that engages with the user."
      allow_file_upload: true
  cpus:
    - cpu: MistralSmall
      title: Mistral Small
    - cpu: MistralMedium
      title: Mistral Medium
    - cpu: MistralLarge
      title: Mistral Large
    - cpu: GPT3.5-turbo
      title: GPT3.5 Turbo
    - cpu: GPT4-turbo
      title: GPT4 Turbo
      default: true
    - cpu: ClaudeOpus
      title: Claude Opus
    - cpu: ClaudeSonnet
      title: Claude Sonnet
    - cpu: ClaudeHaiku
      title: Claude Haiku
