apiVersion: server.eidolonai.com/v1alpha1
kind: Agent
metadata:
  name: search_agent
spec:
  implementation: WebSearchAgent
---
apiVersion: server.eidolonai.com/v1alpha1
kind: Agent
metadata:
  name: scraping_agent
spec:
  implementation: WebScrapingAgent
---
apiVersion: server.eidolonai.com/v1alpha1
kind: Agent
metadata:
  name: research_agent
spec:
  implementation: WebResearcher
  search_agent: search_agent
  scraping_agent: scraping_agent
