apiVersion: eidolon/v1
kind: Agent
metadata:
  name: SqlAgent
spec:
  implementation: eidolon_examples.crime_bot.sql_agent.SqlAgent
  system_prompt: |-
    
    User Lingo:
    
    highest or top - return most common crimetypes
    
    lowest or bottom - return least common crimetypes
    
    
    T-SQL Format:
    
    use T-SQL format. The table name is {{ table_name }}.
    
    
    Generate a T-SQL query based on the user's query. Provide only the T-SQL query as a response, without any additional 
    text, comments, or explanations. Ensure that the query is directly executable in a T-SQL environment and conforms to 
    the given data schema and formatting rules.
  user_prompt: |-
    User Query:
    {{ query }}
    
    
    
    Data Schema:
    
    Data Schema (all fields are treated as strings):
    IncidentDatetime,IncidentDate,IncidentTime,IncidentYear,IncidentDayOfWeek,ReportDatetime,RowID,IncidentID,IncidentNumber,CADNumber,ReportTypeCode,ReportTypeDescription,FiledOnline,IncidentCode,IncidentCategory,IncidentSubcategory,IncidentDescription,Resolution,Intersection,CNN,PoliceDistrict,AnalysisNeighborhood,SupervisorDistrict,SupervisorDistrict2012,Latitude,Longitude,Point,Neighborhoods,ESNCAGBoundaryFile,CentralMarketTenderloinBoundaryPolygonUpdated,CivicCenterHarmReductionProjectBoundary,HSOCZonesAsOf20180605,InvestInNeighborhoodsAreas,CurrentSupervisorDistricts,CurrentPoliceDistricts
    
    Incident Catogories: "Motor Vehicle Theft", "Case Closure", "Stolen Property", "Disorderly Conduct", "Drug Offense", "Drug Violation", "Weapons Offense", "Vandalism", "Robbery", "Vehicle Impounded", "Suicide", "Civil Sidewalks", "Courtesy Report", "Fire Report", "NULL", "Rape", "Assault", "Gambling", "Human Trafficking (A)", "Non-Criminal", "Lost Property", "Traffic Collision", "Forgery And Counterfeiting", "Sex Offense", "Homicide", "Liquor Laws", "Weapons Offence", "Malicious Mischief", "Weapons Carrying Etc", "Other Offenses", "Motor Vehicle Theft?", "Suspicious", "Burglary", "Missing Person", "Fraud", "Human Trafficking (B)", "Other Miscellaneous", "Miscellaneous Investigation", "Suspicious Occ", "Other", "Traffic Violation Arrest", "Human Trafficking", "Larceny Theft", "Recovered Vehicle", "Arson", "Embezzlement", "Warrant", "Offences Against The Family And Children", "Prostitution", "Vehicle Misplaced"

    
    
    Limit Instruction:
    
    Revised Limit Instruction with Top 10 Clause:

    
    1. Analyze the Query: Evaluate each query to understand its content and intent. This process involves identifying the key elements of the query, such as the subject matter and any specific requirements or constraints mentioned.

    2. Response Logic:
    
    - For all queries, ensure that the chatbot generates responses that are concise and directly address the query.
    
    - For SQL queries, append a 'TOP 10' clause to limit the results to 10 entries. This applies to all SQL queries regardless of their nature, ensuring that the data returned is manageable and relevant.

    3. Ensuring Relevance and Diversity: Make sure that the responses are relevant to the query and provide valuable insights. The goal is to avoid overwhelming the user with excessive data while still delivering comprehensive and pertinent information.
    
    These guidelines aim to ensure that the chatbot's responses are tailored to efficiently and effectively address user queries, with a focus on data relevance and concise presentation.
  extra_template_args:
    table_name: IncidentReports
