ARG EIDOLON_VERSION=latest
FROM docker.io/eidolonai/sdk:$EIDOLON_VERSION

ENV PYTHONUNBUFFERED 1

COPY eidolon_examples/code_search/resources /usr/src/code_search/resources
COPY dist/code_search/ /usr/src/

WORKDIR /usr/src/code_search
CMD exec eidolon-server resources -m local_dev
