apiVersion: eidolon/v1
kind: Agent
metadata:
  name: CompanyResearcher
spec:
  apu:
    logic_units:
      - implementation: Search
      - implementation: Browser
      - implementation: eidolon_examples.venture_search_agent.api_logic_unit.ApiLogicUnit
        root_call_url: "https://api.harmonic.ai"
        open_api_location: "https://api.harmonic.ai/openapi.json"
        key_env_var: "HARMONIC_API_KEY"
        key_query_param: "apikey"
        operations_to_expose:
          - name: "enrich_company"
            description: "Enriches a company with information from the Harmonic API"
            path: "/companies"
            method: "post"
            result_filters:
              - "$.entity_urn"
              - "$.name"
              - "$.website"
              - "$.logo_url"
              - "$.legal_name"
              - "$.description"
              - "$.stage"
              - "$.funding"

  description: "Creates company summaries"
  system_prompt: |-
    You are a helpful venture fund research assistant. Use the tools at your disposal to find information about companies.
    First try to use the tool 'enrich_company' to get as much information as you can about the company.
    Next, use the browser tool to find the company's website and scrape off as much information as you can.
    Continue using your tools to research until you know as many fields for your output. You may follow links on any webpage you find.
  actions:
    - name: "search_company"
      user_prompt: |-
        Give me a summary of {{ company_name }}.
        Company website {{url}}
        Company Category {{category}}
      output_schema:
        type: object
        properties:
          description:
            type: string
            description: "A 2 sentence summary of the company"
          stage:
            type: string
            description: "The stage of the company. Legal values are Pre-Seed, Seed, a letter (like A, B, C, ...), Publicly Traded, or 'unknown'"
          market_size:
            type: string
            description: "The market size or market cap of the company. This value can be a number or a range and should be followed by the currency"
          business_model:
            type: string
            description: "How does the company make money?"
          logo_url:
            type: string
            description: "URL of the company logo. Can be found in the company's website. Use the logo to identify the company or the favicon if available"
          other_information:
            type: string
            description: "Any other information you found that is relevant for a venture fund"
