apiVersion: eidolon/v1
kind: Agent
metadata:
  name: venture-copilot
spec:
  apu:
    exponential_backoff: 2
  description: top level copilot agent
  implementation: eidolon_examples.venture_search_agent.venture_copilot.VentureCopilot
