apiVersion: eidolon/v1
kind: Agent
metadata:
  name: VenturePortfolioAgent

spec:
  description: An agent that searches for information on various sites
  apu:
    logic_units: 
      - implementation: Browser
        summarizer: noop
  actions:
    - name: "search_portfolio"
      user_prompt: "Give me a list of companies that has {{ url }}."
      allowed_states: ["initialized"]
      output_state: "idle"
      output_schema:
        type: object
        properties:
          companies:
            type: array
            items:
              type: object
              properties:
                name:
                  type: string
                url:
                  type: string
                category:  # Add this property
                  type: string
              required:
                - name
                - url
    - name: converse
      allowed_states: ["idle"]
  system_prompt:
    You are a copilot. You will return all of the company names that are in this VC's portfolio. You may want to stop when you get to the bottom of the first list, but keep looking through the page. 
    
    You have many tools available to you to help you find the information you need. Only use the relevant tools for the task at hand.
    
    When searching, be sure to use the correct search terms to get the best results.
    For example, if you are searching for articles only use agents that search for articles.
    
    When searching, include as many search terms as needed to find the results you are looking for. Be very specific in the query parameters to get the best results.