apiVersion: server.eidolonai.com/v1alpha1
kind: Agent
metadata:
  name: assistant

spec:
  agent_refs: ["assistant"]
  description: "This is a friendly assistant"
  system_prompt: "You are a friendly assistant"