apiVersion: eidolon/v1
kind: Agent

metadata:
  name: OpenAIAssistants

spec:
  implementation: GenericAgent
  description: "This is an example of a generic agent which can be used to create a conversational agent."
  cpu:
    implementation: "eidolon_ai_sdk.cpu.open_ai_assistants_cpu.OpenAIAssistantsCPU"
    spec:
      logic_units:
        - implementation: "eidolon_examples.hello_world.SimpleTool.MathsTool"

  system_prompt: "You are a machine which follows instructions and returns a summary of your actions."
  user_prompt: "{{instruction}}"
  input_schema:
    instruction:
      type: string
  output_schema: 'str'
  files: 'single'
