apiVersion: eidolon/v1
kind: Agent

metadata:
  name: SpeechAgent

spec:
  implementation: "eidolon_examples.hello_world.AutonomousSpeechAgent.AutonomousSpeechAgent"
  description: "This is an example of a generic agent which can be used to create a conversational agent."
  system_prompt: "You are a machine which follows instructions and returns a summary of your actions."
  user_prompt: "{{instruction}}"
  question_json_schema:
    type: object
    properties:
      instruction:
        type: string
  output_schema: 'str'