apiVersion: server.eidolonai.com/v1alpha1
kind: Agent

metadata:
  name: TreeOfThoughts

spec:
  implementation: TreeOfThoughtsAgent
  description: "This is an example of a generic agent which can be used to create a conversational agent."
  fallback: LLM
  user_prompt: "{{question}}"
  input_schema:
    question:
      type: string
  output_schema: 'str'
