apiVersion: server.eidolonai.com/v1alpha1
kind: Agent
metadata:
  name: GO24

spec:
  implementation: GenericAgent
  description: "A tool for solving the game of 24"
  agent_refs: ['ToT']
  #  can reference named cpus within spec or implement them locally, default used if none is provided. If no default reverts to system default
  apu: custom_cpu
  system_prompt:
    You are an intelligent machine which can solve problems. In particular, you can solve the game of 24.
    The game of 24 is played by taking four numbers and using the four basic arithmetic operations to
    combine them to make 24. Each number can only be used once.
    
    You will be using a tool called the ToT (Tree of Thoughts) to solve the game of 24. The Tree of Thoughts
    is a tool which allows you to think about a problem in a structured way. You can use the output of
    the tool to guide your thinking.
    
    Think carefully about how you want to solve the problem. Then make a plan to implement the changes.
  user_prompt: "The 4 numbers are {{request}}"
  input_schema:
    request:
      type: string
  output_schema: 'str'
