name: Build and Push Demo Docker Images
on:
  workflow_run:
    workflows: [ "Bump Examples Version" ]
    types:
      - completed
  workflow_dispatch:

jobs:
  docker_push_chatbot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: make chatbot_push
        working-directory: examples
