name: Build and Push WebUI Docker Image
on:
  workflow_run:
    workflows: [ "Bump WebUI Version" ]
    types:
      - completed
  workflow_dispatch:

jobs:
  docker_push_webui:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: docker build -t docker.io/eidolonai/webui -t docker.io/eidolonai/webui:$(npm pkg get version | tr -d '"') .
        working-directory: webui
      - run: docker push docker.io/eidolonai/webui
        working-directory: webui
      - run: docker push docker.io/eidolonai/webui:$(npm pkg get version | tr -d '"')
        working-directory: webui
